enum ApiRoutes {
  listOprations = "oprations/list",
  // listServices = "services/list",
  // listProducts = "products/list",
  // listCategories = "categories/list",
  // listReviews = "reviews/list",
  // listBanners = "banners/list",
  // getShopById = "shops/get",
  // getProductById = "products/get",
  // getServiceById = "services/get",
  // addToCart = "carts/item",
  // requestService = "requests/create",
  // getCart = "carts/get",
  // removeFromCart = "/carts/item",
  // flushCart = "carts/flush",
  // createOrder = "orders/create",
  // getWishlist = "wishlists/get",
  // addToWishlist = "wishlists/item",
  // removeFromWishlist = "wishlists/item",
  // listServicesRequested = "requests/list",
  // listOrders = "orders/list",
  // uploadImage = "image",
  // register = "register",
  // login = "login",
  // addReview = "reviews/create",
}
export default ApiRoutes;
